"use client"

import { FileDown } from "lucide-react"
import { Button } from "@/components/ui/button"
import type { DesignIssue } from "./issues-sidebar"

interface DownloadPdfButtonProps {
  fileName: string | null
  issues: DesignIssue[]
  disabled: boolean
}

export function DownloadPdfButton({ fileName, issues, disabled }: DownloadPdfButtonProps) {
  const handleDownload = () => {
    // Generate PDF content
    const content = generatePdfContent(fileName, issues)
    
    // Create a blob and download
    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = `${fileName?.replace(/\.(step|stp)$/i, "") || "cad"}-validation-report.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  return (
    <Button
      onClick={handleDownload}
      disabled={disabled}
      className="gap-2"
      variant="default"
    >
      <FileDown className="h-4 w-4" />
      Download Report
    </Button>
  )
}

function generatePdfContent(fileName: string | null, issues: DesignIssue[]): string {
  const criticalCount = issues.filter((i) => i.severity === "critical").length
  const warningCount = issues.filter((i) => i.severity === "warning").length
  const passedCount = issues.filter((i) => i.severity === "passed").length

  let content = `
╔══════════════════════════════════════════════════════════════════╗
║                    CAD VALIDATION REPORT                         ║
╚══════════════════════════════════════════════════════════════════╝

File: ${fileName || "N/A"}
Generated: ${new Date().toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                           SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔴 Critical Issues: ${criticalCount}
🟡 Warnings: ${warningCount}
🟢 Passed Checks: ${passedCount}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                         DETAILED REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`

  issues.forEach((issue, index) => {
    const severityIcon =
      issue.severity === "critical" ? "🔴" : issue.severity === "warning" ? "🟡" : "🟢"

    content += `
[${index + 1}] ${severityIcon} ${issue.title.toUpperCase()}
────────────────────────────────────────────────────────────────────

Severity: ${issue.severity.toUpperCase()}
${issue.location ? `Location: ${issue.location}\n` : ""}
Description:
${issue.description}

💡 AI Suggestion:
${issue.aiSuggestion}

`
  })

  content += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                        END OF REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by CAD Validator
`

  return content
}
